### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Ad-Blokker** [tvdstaaij/telegram-json-backup#5]
It gives this error message:

![back up python](https://cloud.githubusercontent.com/assets/14195799/9794272/6fb4c3a8-57ea-11e5-8195-68458ec12506.JPG)

**Comment by tvdstaaij** [comment]
Your tg is built with libpython2. As mentioned in the readme the script requires libpython3. So you'll have to rebuild it against Python 3, see #1 for details.

**Comment by tvdstaaij** [comment]
I noticed you're using Ubuntu. I don't use Ubuntu myself but I think this should work:
1. `sudo apt-get install libpython3-dev`
2. Completely rebuild telegram-cli: `make clean && ./configure && make`

**Comment by Ad-Blokker** [comment]
Thank you very much! This worked :)
